<?xml version="1.0" encoding="utf-8"?><Database Name="usuariosasain" Class="DatosUsuariosDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=KRATOS\SQLEXPRESS;Initial Catalog=usuariosasain;Integrated Security=True" SettingsObjectName="UsuariosAsain.Properties.Settings" SettingsPropertyName="usuariosasainConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Asistencia" Member="Asistencia">
    <Type Name="Asistencia">
      <Column Name="IdAsistencia" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Fecha" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Comentario" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="Usuarios_Asistencia" Member="Usuario" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Usuario" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.[Estado civil]" Member="Estado_civil">
    <Type Name="Estado_civil">
      <Column Name="IdEstadocivil" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Estadocivil" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
      <Association Name="Estado_civil_Usuarios" Member="Usuario" ThisKey="IdEstadocivil" OtherKey="IdEstadocivil" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.Estudios" Member="Estudios">
    <Type Name="Estudios">
      <Column Name="IdEstudios" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Estudios" Member="Estudios1" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
      <Association Name="Estudios_Usuarios" Member="Usuario" ThisKey="IdEstudios" OtherKey="IdEstudios" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.Intereses" Member="Interes">
    <Type Name="Interes">
      <Column Name="IdIntereses" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Intereses" Member="Intereses1" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
      <Association Name="Intereses_Usuarios" Member="Usuario" ThisKey="IdIntereses" OtherKey="IdIntereses" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.Origen" Member="Origen">
    <Type Name="Origen">
      <Column Name="IdOrigen" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="País" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
      <Association Name="Origen_Usuarios" Member="Usuario" ThisKey="IdOrigen" OtherKey="IdOrigen" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.Profesión" Member="Profesión">
    <Type Name="Profesión">
      <Column Name="IdProfesión" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Profesión" Member="Profesión1" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
      <Association Name="Profesión_Usuarios" Member="Usuario" ThisKey="IdProfesión" OtherKey="IdProfesión" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.[Situación laboral]" Member="Situación_laboral">
    <Type Name="Situación_laboral">
      <Column Name="IdSituaciónlaboral" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Situaciónlaboral" Type="System.String" DbType="NVarChar(512) NOT NULL" CanBeNull="false" />
      <Association Name="Situación_laboral_Usuarios" Member="Usuario" ThisKey="IdSituaciónlaboral" OtherKey="IdSituaciónlaboral" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.[Tipos de usuario]" Member="Tipos_de_usuario">
    <Type Name="Tipos_de_usuario">
      <Column Name="IdTipoUsuario" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="TipoUsuario" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="Tipos_de_usuario_Usuarios" Member="Usuario" ThisKey="IdTipoUsuario" OtherKey="IdTipoUsuario" Type="Usuario" />
    </Type>
  </Table>
  <Table Name="dbo.Usuarios" Member="Usuario">
    <Type Name="Usuario">
      <Column Name="IdUsuario" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Apellidos" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IdProfesión" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Dirección" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Ciudad" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="EdoOProv" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CódPostal" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Región" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IdOrigen" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreCompañía" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="Cargo" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="TeléfonoTrabajo" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="ExtensiónTrabajo" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="TeléfonoMóvil" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NúmFax" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="NomCorreoElectrónico" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="[Fecha nacimiento]" Member="Fecha_nacimiento" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="FechaÚltimaReunión" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IdTipoUsuario" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdEstudios" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Notas" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IdEstadocivil" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NombreCónyuge" Type="System.String" DbType="NVarChar(512)" CanBeNull="true" />
      <Column Name="InteresesCónyuges" Type="System.String" DbType="NVarChar(1024)" CanBeNull="true" />
      <Column Name="NombresNiños" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="CiudadNatal" Type="System.String" DbType="NVarChar(255)" CanBeNull="true" />
      <Column Name="IdIntereses" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IdSituaciónlaboral" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Usuarios_Asistencia" Member="Asistencia" ThisKey="IdUsuario" OtherKey="IdUsuario" Type="Asistencia" />
      <Association Name="Estado_civil_Usuarios" Member="Estado_civil" ThisKey="IdEstadocivil" OtherKey="IdEstadocivil" Type="Estado_civil" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Estudios_Usuarios" Member="Estudios" ThisKey="IdEstudios" OtherKey="IdEstudios" Type="Estudios" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Intereses_Usuarios" Member="Interes" ThisKey="IdIntereses" OtherKey="IdIntereses" Type="Interes" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Origen_Usuarios" Member="Origen" ThisKey="IdOrigen" OtherKey="IdOrigen" Type="Origen" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Profesión_Usuarios" Member="Profesión" ThisKey="IdProfesión" OtherKey="IdProfesión" Type="Profesión" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Situación_laboral_Usuarios" Member="Situación_laboral" ThisKey="IdSituaciónlaboral" OtherKey="IdSituaciónlaboral" Type="Situación_laboral" IsForeignKey="true" DeleteRule="SET NULL" />
      <Association Name="Tipos_de_usuario_Usuarios" Member="Tipos_de_usuario" ThisKey="IdTipoUsuario" OtherKey="IdTipoUsuario" Type="Tipos_de_usuario" IsForeignKey="true" DeleteRule="SET NULL" />
    </Type>
  </Table>
</Database>